var annotated_dup =
[
    [ "atlas", "namespaceatlas.html", [
      [ "event", null, [
        [ "bus", "classatlas_1_1event_1_1bus.html", null ],
        [ "collision_enter", "structatlas_1_1event_1_1collision__enter.html", null ],
        [ "collision_exit", "structatlas_1_1event_1_1collision__exit.html", null ],
        [ "collision_persisted", "structatlas_1_1event_1_1collision__persisted.html", null ],
        [ "listener", "classatlas_1_1event_1_1listener.html", null ],
        [ "scene_transition", "structatlas_1_1event_1_1scene__transition.html", null ]
      ] ],
      [ "physics", null, [
        [ "broad_phase_layer_interface", "classatlas_1_1physics_1_1broad__phase__layer__interface.html", null ],
        [ "contact_event", "structatlas_1_1physics_1_1contact__event.html", null ],
        [ "contact_listener", "classatlas_1_1physics_1_1contact__listener.html", null ],
        [ "engine", "classatlas_1_1physics_1_1engine.html", "classatlas_1_1physics_1_1engine" ],
        [ "jolt_context", "classatlas_1_1physics_1_1jolt__context.html", "classatlas_1_1physics_1_1jolt__context" ],
        [ "jolt_settings", "structatlas_1_1physics_1_1jolt__settings.html", "structatlas_1_1physics_1_1jolt__settings" ],
        [ "matrix4", "structatlas_1_1physics_1_1matrix4.html", null ],
        [ "matrix4< JPH::Mat44 >", "structatlas_1_1physics_1_1matrix4_3_01JPH_1_1Mat44_01_4.html", null ],
        [ "object_layer_pair_filter", "classatlas_1_1physics_1_1object__layer__pair__filter.html", null ],
        [ "object_vs_broadphase_layer", "classatlas_1_1physics_1_1object__vs__broadphase__layer.html", null ],
        [ "physics_context", "classatlas_1_1physics_1_1physics__context.html", "classatlas_1_1physics_1_1physics__context" ],
        [ "quaternion", "structatlas_1_1physics_1_1quaternion.html", null ],
        [ "vector3", "structatlas_1_1physics_1_1vector3.html", null ],
        [ "vector3< JPH::Double3 >", "structatlas_1_1physics_1_1vector3_3_01JPH_1_1Double3_01_4.html", null ],
        [ "vector3< JPH::DVec3 >", "structatlas_1_1physics_1_1vector3_3_01JPH_1_1DVec3_01_4.html", null ],
        [ "vector3< JPH::Float3 >", "structatlas_1_1physics_1_1vector3_3_01JPH_1_1Float3_01_4.html", null ],
        [ "vector3< JPH::Vec3 >", "structatlas_1_1physics_1_1vector3_3_01JPH_1_1Vec3_01_4.html", null ],
        [ "vector4", "structatlas_1_1physics_1_1vector4.html", null ],
        [ "vector4< JPH::Float4 >", "structatlas_1_1physics_1_1vector4_3_01JPH_1_1Float4_01_4.html", null ],
        [ "vector4< JPH::Vec4 >", "structatlas_1_1physics_1_1vector4_3_01JPH_1_1Vec4_01_4.html", null ]
      ] ],
      [ "tag", "namespaceatlas_1_1tag.html", [
        [ "editor", "structatlas_1_1tag_1_1editor.html", null ],
        [ "serialize", "structatlas_1_1tag_1_1serialize.html", null ]
      ] ],
      [ "ui", null, [
        [ "block", "structatlas_1_1ui_1_1block.html", null ],
        [ "dockspace", "classatlas_1_1ui_1_1dockspace.html", null ],
        [ "menu_bar_exception", "classatlas_1_1ui_1_1menu__bar__exception.html", null ],
        [ "menu_item", "classatlas_1_1ui_1_1menu__item.html", null ]
      ] ],
      [ "vulkan", null, [
        [ "camera_ubo", "structatlas_1_1vulkan_1_1camera__ubo.html", null ],
        [ "device", "classatlas_1_1vulkan_1_1device.html", "classatlas_1_1vulkan_1_1device" ],
        [ "geometry_uniform", "structatlas_1_1vulkan_1_1geometry__uniform.html", null ],
        [ "global_ubo", "structatlas_1_1vulkan_1_1global__ubo.html", null ],
        [ "imgui_context", "classatlas_1_1vulkan_1_1imgui__context.html", null ],
        [ "instance_context", "classatlas_1_1vulkan_1_1instance__context.html", "classatlas_1_1vulkan_1_1instance__context" ],
        [ "light_scene_ubo", "structatlas_1_1vulkan_1_1light__scene__ubo.html", null ],
        [ "material_uniform", "structatlas_1_1vulkan_1_1material__uniform.html", null ],
        [ "mesh", "classatlas_1_1vulkan_1_1mesh.html", null ],
        [ "physical_device", "classatlas_1_1vulkan_1_1physical__device.html", null ],
        [ "point_light_ubo", "structatlas_1_1vulkan_1_1point__light__ubo.html", null ],
        [ "render_system", "classatlas_1_1vulkan_1_1render__system.html", null ],
        [ "shader_resource_group", "classatlas_1_1vulkan_1_1shader__resource__group.html", "classatlas_1_1vulkan_1_1shader__resource__group" ],
        [ "surface_properties", "structatlas_1_1vulkan_1_1surface__properties.html", null ],
        [ "swapchain", "classatlas_1_1vulkan_1_1swapchain.html", null ],
        [ "vertex_input", "structatlas_1_1vulkan_1_1vertex__input.html", null ],
        [ "window_context", "classatlas_1_1vulkan_1_1window__context.html", null ]
      ] ],
      [ "application", "classatlas_1_1application.html", null ],
      [ "application_settings", "structatlas_1_1application__settings.html", null ],
      [ "box_collider", "structatlas_1_1box__collider.html", null ],
      [ "capsule_collider", "structatlas_1_1capsule__collider.html", null ],
      [ "console_log_manager", "classatlas_1_1console__log__manager.html", null ],
      [ "directional_light", "structatlas_1_1directional__light.html", null ],
      [ "game_object", "classatlas_1_1game__object.html", null ],
      [ "graphics_context", "classatlas_1_1graphics__context.html", null ],
      [ "joystick_button", "structatlas_1_1joystick__button.html", null ],
      [ "joystick_info", "structatlas_1_1joystick__info.html", null ],
      [ "material_metadata", "structatlas_1_1material__metadata.html", null ],
      [ "math_generic", "structatlas_1_1math__generic.html", null ],
      [ "matrix2", "structatlas_1_1matrix2.html", null ],
      [ "matrix3", "structatlas_1_1matrix3.html", null ],
      [ "matrix4", "structatlas_1_1matrix4.html", null ],
      [ "mesh_source", "structatlas_1_1mesh__source.html", null ],
      [ "perspective_camera", "structatlas_1_1perspective__camera.html", null ],
      [ "physics_body", "structatlas_1_1physics__body.html", null ],
      [ "point_light", "structatlas_1_1point__light.html", null ],
      [ "projection_view", "structatlas_1_1projection__view.html", null ],
      [ "renderer_system", "classatlas_1_1renderer__system.html", null ],
      [ "scene", "classatlas_1_1scene.html", null ],
      [ "serializer", "classatlas_1_1serializer.html", "classatlas_1_1serializer" ],
      [ "sphere_collider", "structatlas_1_1sphere__collider.html", null ],
      [ "surface_properties", "structatlas_1_1surface__properties.html", null ],
      [ "system_registry", "classatlas_1_1system__registry.html", null ],
      [ "transform", "structatlas_1_1transform.html", null ],
      [ "vector2", "structatlas_1_1vector2.html", null ],
      [ "vector2< glm::highp_vec2 >", "structatlas_1_1vector2_3_01glm_1_1highp__vec2_01_4.html", null ],
      [ "vector3", "structatlas_1_1vector3.html", null ],
      [ "vector3< glm::highp_vec3 >", "structatlas_1_1vector3_3_01glm_1_1highp__vec3_01_4.html", null ],
      [ "vector3< JPH::Vec3 >", "structatlas_1_1vector3_3_01JPH_1_1Vec3_01_4.html", null ],
      [ "vector4", "structatlas_1_1vector4.html", null ],
      [ "vector4< glm::highp_vec4 >", "structatlas_1_1vector4_3_01glm_1_1highp__vec4_01_4.html", null ],
      [ "window", "classatlas_1_1window.html", null ],
      [ "window_params", "structatlas_1_1window__params.html", null ],
      [ "world", "classatlas_1_1world.html", null ]
    ] ],
    [ "std", null, [
      [ "hash< vk::vertex_input >", "structstd_1_1hash_3_01vk_1_1vertex__input_01_4.html", null ]
    ] ],
    [ "YAML", null, [
      [ "convert< atlas::body_layer >", "structYAML_1_1convert_3_01atlas_1_1body__layer_01_4.html", null ],
      [ "convert< atlas::body_type >", "structYAML_1_1convert_3_01atlas_1_1body__type_01_4.html", null ],
      [ "convert< atlas::box_collider >", "structYAML_1_1convert_3_01atlas_1_1box__collider_01_4.html", null ],
      [ "convert< atlas::capsule_collider >", "structYAML_1_1convert_3_01atlas_1_1capsule__collider_01_4.html", null ],
      [ "convert< atlas::mesh_source >", "structYAML_1_1convert_3_01atlas_1_1mesh__source_01_4.html", null ],
      [ "convert< atlas::physics_body >", "structYAML_1_1convert_3_01atlas_1_1physics__body_01_4.html", null ],
      [ "convert< atlas::point_light >", "structYAML_1_1convert_3_01atlas_1_1point__light_01_4.html", null ],
      [ "convert< atlas::sphere_collider >", "structYAML_1_1convert_3_01atlas_1_1sphere__collider_01_4.html", null ],
      [ "convert< glm::vec2 >", "structYAML_1_1convert_3_01glm_1_1vec2_01_4.html", null ],
      [ "convert< glm::vec3 >", "structYAML_1_1convert_3_01glm_1_1vec3_01_4.html", null ],
      [ "convert< glm::vec4 >", "structYAML_1_1convert_3_01glm_1_1vec4_01_4.html", null ]
    ] ]
];