var annotated_dup =
[
    [ "atlas", null, [
      [ "event", null, [
        [ "collision_enter", "structatlas_1_1event_1_1collision__enter.html", null ],
        [ "collision_exit", "structatlas_1_1event_1_1collision__exit.html", null ],
        [ "collision_persisted", "structatlas_1_1event_1_1collision__persisted.html", null ],
        [ "event_bus", "classatlas_1_1event_1_1event__bus.html", null ],
        [ "joystick_button", "structatlas_1_1event_1_1joystick__button.html", null ],
        [ "joystick_info", "structatlas_1_1event_1_1joystick__info.html", null ],
        [ "listener", "classatlas_1_1event_1_1listener.html", null ],
        [ "scene_transition", "structatlas_1_1event_1_1scene__transition.html", null ]
      ] ],
      [ "memory", null, [
        [ "detail", null, [
          [ "is_array_like", "structatlas_1_1memory_1_1detail_1_1is__array__like.html", null ],
          [ "is_array_like< std::array< T, N > >", "structatlas_1_1memory_1_1detail_1_1is__array__like_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", null ],
          [ "is_array_like< T[N]>", "structatlas_1_1memory_1_1detail_1_1is__array__like_3_01T_0fN_0e_4.html", null ],
          [ "rc", "structatlas_1_1memory_1_1detail_1_1rc.html", null ],
          [ "ref_info", "structatlas_1_1memory_1_1detail_1_1ref__info.html", "structatlas_1_1memory_1_1detail_1_1ref__info" ]
        ] ],
        [ "enable_strong_from_this", "classatlas_1_1memory_1_1enable__strong__from__this.html", "classatlas_1_1memory_1_1enable__strong__from__this" ],
        [ "optional_ptr", "classatlas_1_1memory_1_1optional__ptr.html", "classatlas_1_1memory_1_1optional__ptr" ],
        [ "strong_ptr", "classatlas_1_1memory_1_1strong__ptr.html", "classatlas_1_1memory_1_1strong__ptr" ],
        [ "strong_ptr_only_token", "classatlas_1_1memory_1_1strong__ptr__only__token.html", null ],
        [ "weak_ptr", "classatlas_1_1memory_1_1weak__ptr.html", "classatlas_1_1memory_1_1weak__ptr" ]
      ] ],
      [ "physics", "namespaceatlas_1_1physics.html", [
        [ "broad_phase_layer_interface", "classatlas_1_1physics_1_1broad__phase__layer__interface.html", "classatlas_1_1physics_1_1broad__phase__layer__interface" ],
        [ "contact_event", "structatlas_1_1physics_1_1contact__event.html", null ],
        [ "contact_listener", "classatlas_1_1physics_1_1contact__listener.html", "classatlas_1_1physics_1_1contact__listener" ],
        [ "jolt_config", "structatlas_1_1physics_1_1jolt__config.html", "structatlas_1_1physics_1_1jolt__config" ],
        [ "jolt_context", "classatlas_1_1physics_1_1jolt__context.html", "classatlas_1_1physics_1_1jolt__context" ],
        [ "jolt_settings", "structatlas_1_1physics_1_1jolt__settings.html", "structatlas_1_1physics_1_1jolt__settings" ],
        [ "matrix4", "structatlas_1_1physics_1_1matrix4.html", null ],
        [ "matrix4< JPH::Mat44 >", "structatlas_1_1physics_1_1matrix4_3_01JPH_1_1Mat44_01_4.html", null ],
        [ "object_layer_pair_filter", "classatlas_1_1physics_1_1object__layer__pair__filter.html", null ],
        [ "object_vs_broadphase_layer", "classatlas_1_1physics_1_1object__vs__broadphase__layer.html", null ],
        [ "physics_context", "classatlas_1_1physics_1_1physics__context.html", "classatlas_1_1physics_1_1physics__context" ],
        [ "physics_engine", "classatlas_1_1physics_1_1physics__engine.html", "classatlas_1_1physics_1_1physics__engine" ],
        [ "quaternion", "structatlas_1_1physics_1_1quaternion.html", null ],
        [ "vector3", "structatlas_1_1physics_1_1vector3.html", null ],
        [ "vector3< JPH::Double3 >", "structatlas_1_1physics_1_1vector3_3_01JPH_1_1Double3_01_4.html", null ],
        [ "vector3< JPH::DVec3 >", "structatlas_1_1physics_1_1vector3_3_01JPH_1_1DVec3_01_4.html", null ],
        [ "vector3< JPH::Float3 >", "structatlas_1_1physics_1_1vector3_3_01JPH_1_1Float3_01_4.html", null ],
        [ "vector3< JPH::Vec3 >", "structatlas_1_1physics_1_1vector3_3_01JPH_1_1Vec3_01_4.html", null ],
        [ "vector4", "structatlas_1_1physics_1_1vector4.html", null ],
        [ "vector4< JPH::Float4 >", "structatlas_1_1physics_1_1vector4_3_01JPH_1_1Float4_01_4.html", null ],
        [ "vector4< JPH::Vec4 >", "structatlas_1_1physics_1_1vector4_3_01JPH_1_1Vec4_01_4.html", null ]
      ] ],
      [ "tag", "namespaceatlas_1_1tag.html", [
        [ "editor", "structatlas_1_1tag_1_1editor.html", null ],
        [ "serialize", "structatlas_1_1tag_1_1serialize.html", null ]
      ] ],
      [ "ui", null, [
        [ "block", "structatlas_1_1ui_1_1block.html", null ],
        [ "dockspace", "classatlas_1_1ui_1_1dockspace.html", null ],
        [ "menu_bar_exception", "classatlas_1_1ui_1_1menu__bar__exception.html", null ],
        [ "menu_item", "classatlas_1_1ui_1_1menu__item.html", null ]
      ] ],
      [ "vk", null, [
        [ "camera_ubo", "structatlas_1_1vk_1_1camera__ubo.html", null ],
        [ "geometry_uniform", "structatlas_1_1vk_1_1geometry__uniform.html", null ],
        [ "global_ubo", "structatlas_1_1vk_1_1global__ubo.html", null ],
        [ "hud_data", "structatlas_1_1vk_1_1hud__data.html", null ],
        [ "imgui_context", "classatlas_1_1vk_1_1imgui__context.html", null ],
        [ "material_uniform", "structatlas_1_1vk_1_1material__uniform.html", null ],
        [ "mesh", "classatlas_1_1vk_1_1mesh.html", "classatlas_1_1vk_1_1mesh" ],
        [ "shader_resource_group", "classatlas_1_1vk_1_1shader__resource__group.html", "classatlas_1_1vk_1_1shader__resource__group" ],
        [ "surface_properties", "structatlas_1_1vk_1_1surface__properties.html", null ],
        [ "vertex_input", "structatlas_1_1vk_1_1vertex__input.html", null ],
        [ "vk_context", "classatlas_1_1vk_1_1vk__context.html", null ],
        [ "vk_driver", "classatlas_1_1vk_1_1vk__driver.html", "classatlas_1_1vk_1_1vk__driver" ],
        [ "vk_physical_driver", "classatlas_1_1vk_1_1vk__physical__driver.html", "classatlas_1_1vk_1_1vk__physical__driver" ],
        [ "vk_renderer", "classatlas_1_1vk_1_1vk__renderer.html", null ],
        [ "vk_swapchain", "classatlas_1_1vk_1_1vk__swapchain.html", "classatlas_1_1vk_1_1vk__swapchain" ],
        [ "vk_window", "classatlas_1_1vk_1_1vk__window.html", null ]
      ] ],
      [ "application", "classatlas_1_1application.html", "classatlas_1_1application" ],
      [ "application_settings", "structatlas_1_1application__settings.html", null ],
      [ "box_collider", "structatlas_1_1box__collider.html", null ],
      [ "capsule_collider", "structatlas_1_1capsule__collider.html", null ],
      [ "console_log_manager", "classatlas_1_1console__log__manager.html", null ],
      [ "directional_light", "structatlas_1_1directional__light.html", null ],
      [ "exception_block", "structatlas_1_1exception__block.html", null ],
      [ "game_object", "classatlas_1_1game__object.html", "classatlas_1_1game__object" ],
      [ "graphics_context", "classatlas_1_1graphics__context.html", "classatlas_1_1graphics__context" ],
      [ "interpolation", "classatlas_1_1interpolation.html", null ],
      [ "invalid_access_exception", "classatlas_1_1invalid__access__exception.html", "classatlas_1_1invalid__access__exception" ],
      [ "light_scene_ubo", "structatlas_1_1light__scene__ubo.html", null ],
      [ "material_metadata", "structatlas_1_1material__metadata.html", null ],
      [ "math_generic", "structatlas_1_1math__generic.html", null ],
      [ "matrix2", "structatlas_1_1matrix2.html", null ],
      [ "matrix3", "structatlas_1_1matrix3.html", null ],
      [ "matrix4", "structatlas_1_1matrix4.html", null ],
      [ "mesh", "classatlas_1_1mesh.html", null ],
      [ "mesh_source", "structatlas_1_1mesh__source.html", null ],
      [ "perspective_camera", "structatlas_1_1perspective__camera.html", null ],
      [ "physics_body", "structatlas_1_1physics__body.html", "structatlas_1_1physics__body" ],
      [ "point_light", "structatlas_1_1point__light.html", null ],
      [ "point_light_ubo", "structatlas_1_1point__light__ubo.html", null ],
      [ "projection_view", "structatlas_1_1projection__view.html", null ],
      [ "render_context", "classatlas_1_1render__context.html", "classatlas_1_1render__context" ],
      [ "renderer", "classatlas_1_1renderer.html", "classatlas_1_1renderer" ],
      [ "scene", "classatlas_1_1scene.html", "classatlas_1_1scene" ],
      [ "serializer", "classatlas_1_1serializer.html", "classatlas_1_1serializer" ],
      [ "sphere_collider", "structatlas_1_1sphere__collider.html", null ],
      [ "system_registry", "classatlas_1_1system__registry.html", "classatlas_1_1system__registry" ],
      [ "transform", "structatlas_1_1transform.html", "structatlas_1_1transform" ],
      [ "vector2", "structatlas_1_1vector2.html", null ],
      [ "vector2< glm::highp_vec2 >", "structatlas_1_1vector2_3_01glm_1_1highp__vec2_01_4.html", null ],
      [ "vector3", "structatlas_1_1vector3.html", null ],
      [ "vector3< glm::highp_vec3 >", "structatlas_1_1vector3_3_01glm_1_1highp__vec3_01_4.html", null ],
      [ "vector3< JPH::Vec3 >", "structatlas_1_1vector3_3_01JPH_1_1Vec3_01_4.html", null ],
      [ "vector4", "structatlas_1_1vector4.html", null ],
      [ "vector4< glm::highp_vec4 >", "structatlas_1_1vector4_3_01glm_1_1highp__vec4_01_4.html", null ],
      [ "window", "classatlas_1_1window.html", "classatlas_1_1window" ],
      [ "window_settings", "structatlas_1_1window__settings.html", null ],
      [ "world", "classatlas_1_1world.html", "classatlas_1_1world" ]
    ] ],
    [ "std", null, [
      [ "hash<::vk::vertex_input >", "structstd_1_1hash_3_1_1vk_1_1vertex__input_01_4.html", null ]
    ] ],
    [ "YAML", null, [
      [ "convert< atlas::body_layer >", "structYAML_1_1convert_3_01atlas_1_1body__layer_01_4.html", null ],
      [ "convert< atlas::body_type >", "structYAML_1_1convert_3_01atlas_1_1body__type_01_4.html", null ],
      [ "convert< atlas::box_collider >", "structYAML_1_1convert_3_01atlas_1_1box__collider_01_4.html", null ],
      [ "convert< atlas::capsule_collider >", "structYAML_1_1convert_3_01atlas_1_1capsule__collider_01_4.html", null ],
      [ "convert< atlas::mesh_source >", "structYAML_1_1convert_3_01atlas_1_1mesh__source_01_4.html", null ],
      [ "convert< atlas::physics_body >", "structYAML_1_1convert_3_01atlas_1_1physics__body_01_4.html", null ],
      [ "convert< atlas::point_light >", "structYAML_1_1convert_3_01atlas_1_1point__light_01_4.html", null ],
      [ "convert< atlas::sphere_collider >", "structYAML_1_1convert_3_01atlas_1_1sphere__collider_01_4.html", null ],
      [ "convert< glm::vec2 >", "structYAML_1_1convert_3_01glm_1_1vec2_01_4.html", null ],
      [ "convert< glm::vec3 >", "structYAML_1_1convert_3_01glm_1_1vec3_01_4.html", null ],
      [ "convert< glm::vec4 >", "structYAML_1_1convert_3_01glm_1_1vec4_01_4.html", null ]
    ] ]
];