var hierarchy =
[
    [ "atlas::application", "classatlas_1_1application.html", null ],
    [ "atlas::application_settings", "structatlas_1_1application__settings.html", null ],
    [ "atlas::box_collider", "structatlas_1_1box__collider.html", null ],
    [ "JPH::BroadPhaseLayerInterface", null, [
      [ "atlas::physics::broad_phase_layer_interface", "classatlas_1_1physics_1_1broad__phase__layer__interface.html", null ]
    ] ],
    [ "atlas::vk::camera_ubo", "structatlas_1_1vk_1_1camera__ubo.html", null ],
    [ "atlas::capsule_collider", "structatlas_1_1capsule__collider.html", null ],
    [ "atlas::event::collision_enter", "structatlas_1_1event_1_1collision__enter.html", null ],
    [ "atlas::event::collision_exit", "structatlas_1_1event_1_1collision__exit.html", null ],
    [ "atlas::event::collision_persisted", "structatlas_1_1event_1_1collision__persisted.html", null ],
    [ "atlas::vk::command_buffer_settings", "structatlas_1_1vk_1_1command__buffer__settings.html", null ],
    [ "atlas::console_log_manager", "classatlas_1_1console__log__manager.html", null ],
    [ "atlas::physics::contact_event", "structatlas_1_1physics_1_1contact__event.html", null ],
    [ "JPH::ContactListener", null, [
      [ "atlas::physics::contact_listener", "classatlas_1_1physics_1_1contact__listener.html", null ]
    ] ],
    [ "YAML::convert< atlas::body_layer >", "structYAML_1_1convert_3_01atlas_1_1body__layer_01_4.html", null ],
    [ "YAML::convert< atlas::body_type >", "structYAML_1_1convert_3_01atlas_1_1body__type_01_4.html", null ],
    [ "YAML::convert< atlas::box_collider >", "structYAML_1_1convert_3_01atlas_1_1box__collider_01_4.html", null ],
    [ "YAML::convert< atlas::capsule_collider >", "structYAML_1_1convert_3_01atlas_1_1capsule__collider_01_4.html", null ],
    [ "YAML::convert< atlas::physics_body >", "structYAML_1_1convert_3_01atlas_1_1physics__body_01_4.html", null ],
    [ "YAML::convert< atlas::sphere_collider >", "structYAML_1_1convert_3_01atlas_1_1sphere__collider_01_4.html", null ],
    [ "YAML::convert< glm::vec2 >", "structYAML_1_1convert_3_01glm_1_1vec2_01_4.html", null ],
    [ "YAML::convert< glm::vec3 >", "structYAML_1_1convert_3_01glm_1_1vec3_01_4.html", null ],
    [ "YAML::convert< glm::vec4 >", "structYAML_1_1convert_3_01glm_1_1vec4_01_4.html", null ],
    [ "atlas::vk::descriptor_binding_entry", "structatlas_1_1vk_1_1descriptor__binding__entry.html", null ],
    [ "atlas::vk::descriptor_binding_point", "structatlas_1_1vk_1_1descriptor__binding__point.html", null ],
    [ "atlas::vk::descriptor_set_layout", "structatlas_1_1vk_1_1descriptor__set__layout.html", null ],
    [ "atlas::tag::editor", "structatlas_1_1tag_1_1editor.html", null ],
    [ "atlas::memory::enable_strong_from_this< T >", "classatlas_1_1memory_1_1enable__strong__from__this.html", null ],
    [ "atlas::event::event_bus", "classatlas_1_1event_1_1event__bus.html", null ],
    [ "std::false_type", null, [
      [ "atlas::memory::detail::is_array_like< T >", "structatlas_1_1memory_1_1detail_1_1is__array__like.html", null ]
    ] ],
    [ "atlas::vk::global_ubo", "structatlas_1_1vk_1_1global__ubo.html", null ],
    [ "atlas::graphics_context", "classatlas_1_1graphics__context.html", [
      [ "atlas::vk::vk_context", "classatlas_1_1vk_1_1vk__context.html", null ]
    ] ],
    [ "std::hash<::vk::vertex_input >", "structstd_1_1hash_3_1_1vk_1_1vertex__input_01_4.html", null ],
    [ "atlas::vk::hud_data", "structatlas_1_1vk_1_1hud__data.html", null ],
    [ "atlas::vk::image_extent", "structatlas_1_1vk_1_1image__extent.html", null ],
    [ "atlas::vk::imgui_context", "classatlas_1_1vk_1_1imgui__context.html", null ],
    [ "atlas::interpolation", "classatlas_1_1interpolation.html", null ],
    [ "atlas::physics::jolt_config", "structatlas_1_1physics_1_1jolt__config.html", null ],
    [ "atlas::physics::jolt_settings", "structatlas_1_1physics_1_1jolt__settings.html", null ],
    [ "atlas::event::joystick_button", "structatlas_1_1event_1_1joystick__button.html", null ],
    [ "atlas::event::joystick_info", "structatlas_1_1event_1_1joystick__info.html", null ],
    [ "atlas::event::listener< UEvent >", "classatlas_1_1event_1_1listener.html", null ],
    [ "atlas::vk::material_uniform", "structatlas_1_1vk_1_1material__uniform.html", null ],
    [ "atlas::math_generic< T >", "structatlas_1_1math__generic.html", null ],
    [ "atlas::matrix2< T >", "structatlas_1_1matrix2.html", null ],
    [ "atlas::matrix3< T >", "structatlas_1_1matrix3.html", null ],
    [ "atlas::matrix4< T >", "structatlas_1_1matrix4.html", null ],
    [ "atlas::physics::matrix4< T >", "structatlas_1_1physics_1_1matrix4.html", null ],
    [ "atlas::physics::matrix4< JPH::Mat44 >", "structatlas_1_1physics_1_1matrix4_3_01JPH_1_1Mat44_01_4.html", null ],
    [ "atlas::mesh", "classatlas_1_1mesh.html", null ],
    [ "atlas::vk::mesh", "classatlas_1_1vk_1_1mesh.html", null ],
    [ "atlas::mesh_source", "structatlas_1_1mesh__source.html", null ],
    [ "JPH::ObjectLayerPairFilter", null, [
      [ "atlas::physics::object_layer_pair_filter", "classatlas_1_1physics_1_1object__layer__pair__filter.html", null ]
    ] ],
    [ "JPH::ObjectVsBroadPhaseLayerFilter", null, [
      [ "atlas::physics::object_vs_broadphase_layer", "classatlas_1_1physics_1_1object__vs__broadphase__layer.html", null ]
    ] ],
    [ "atlas::memory::optional_ptr< T >", "classatlas_1_1memory_1_1optional__ptr.html", null ],
    [ "atlas::perspective_camera", "structatlas_1_1perspective__camera.html", null ],
    [ "atlas::physics_body", "structatlas_1_1physics__body.html", null ],
    [ "atlas::physics::physics_context", "classatlas_1_1physics_1_1physics__context.html", [
      [ "atlas::physics::jolt_context", "classatlas_1_1physics_1_1jolt__context.html", null ]
    ] ],
    [ "atlas::physics::physics_engine", "classatlas_1_1physics_1_1physics__engine.html", null ],
    [ "atlas::projection_view", "structatlas_1_1projection__view.html", null ],
    [ "atlas::physics::quaternion< T >", "structatlas_1_1physics_1_1quaternion.html", null ],
    [ "atlas::memory::detail::rc< T >", "structatlas_1_1memory_1_1detail_1_1rc.html", null ],
    [ "atlas::memory::detail::ref_info", "structatlas_1_1memory_1_1detail_1_1ref__info.html", null ],
    [ "atlas::reload", "structatlas_1_1reload.html", null ],
    [ "atlas::render_context", "classatlas_1_1render__context.html", [
      [ "atlas::vk::vk_renderer", "classatlas_1_1vk_1_1vk__renderer.html", null ]
    ] ],
    [ "atlas::renderer", "classatlas_1_1renderer.html", null ],
    [ "atlas::vk::renderpass_attachment", "structatlas_1_1vk_1_1renderpass__attachment.html", null ],
    [ "atlas::vk::renderpass_options", "structatlas_1_1vk_1_1renderpass__options.html", null ],
    [ "atlas::scene_object", "classatlas_1_1scene__object.html", null ],
    [ "atlas::scene_scope", "classatlas_1_1scene__scope.html", null ],
    [ "atlas::tag::serialize", "structatlas_1_1tag_1_1serialize.html", null ],
    [ "atlas::serializer", "classatlas_1_1serializer.html", null ],
    [ "atlas::vk::shader_info", "structatlas_1_1vk_1_1shader__info.html", null ],
    [ "atlas::sphere_collider", "structatlas_1_1sphere__collider.html", null ],
    [ "atlas::memory::strong_ptr< T >", "classatlas_1_1memory_1_1strong__ptr.html", null ],
    [ "atlas::memory::strong_ptr_only_token", "classatlas_1_1memory_1_1strong__ptr__only__token.html", null ],
    [ "atlas::vk::surface_properties", "structatlas_1_1vk_1_1surface__properties.html", null ],
    [ "atlas::system_registry", "classatlas_1_1system__registry.html", null ],
    [ "atlas::vk::texture_properties", "structatlas_1_1vk_1_1texture__properties.html", null ],
    [ "atlas::transform", "structatlas_1_1transform.html", null ],
    [ "std::true_type", null, [
      [ "atlas::memory::detail::is_array_like< T[N]>", "structatlas_1_1memory_1_1detail_1_1is__array__like_3_01T_0fN_0e_4.html", null ],
      [ "atlas::memory::detail::is_array_like< std::array< T, N > >", "structatlas_1_1memory_1_1detail_1_1is__array__like_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", null ]
    ] ],
    [ "atlas::vector2< T >", "structatlas_1_1vector2.html", null ],
    [ "atlas::vector2< glm::highp_vec2 >", "structatlas_1_1vector2_3_01glm_1_1highp__vec2_01_4.html", null ],
    [ "atlas::physics::vector3< T >", "structatlas_1_1physics_1_1vector3.html", null ],
    [ "atlas::vector3< T >", "structatlas_1_1vector3.html", null ],
    [ "atlas::vector3< glm::highp_vec3 >", "structatlas_1_1vector3_3_01glm_1_1highp__vec3_01_4.html", null ],
    [ "atlas::physics::vector3< JPH::Double3 >", "structatlas_1_1physics_1_1vector3_3_01JPH_1_1Double3_01_4.html", null ],
    [ "atlas::physics::vector3< JPH::DVec3 >", "structatlas_1_1physics_1_1vector3_3_01JPH_1_1DVec3_01_4.html", null ],
    [ "atlas::physics::vector3< JPH::Float3 >", "structatlas_1_1physics_1_1vector3_3_01JPH_1_1Float3_01_4.html", null ],
    [ "atlas::physics::vector3< JPH::Vec3 >", "structatlas_1_1physics_1_1vector3_3_01JPH_1_1Vec3_01_4.html", null ],
    [ "atlas::vector3< JPH::Vec3 >", "structatlas_1_1vector3_3_01JPH_1_1Vec3_01_4.html", null ],
    [ "atlas::physics::vector4< T >", "structatlas_1_1physics_1_1vector4.html", null ],
    [ "atlas::vector4< T >", "structatlas_1_1vector4.html", null ],
    [ "atlas::vector4< glm::highp_vec4 >", "structatlas_1_1vector4_3_01glm_1_1highp__vec4_01_4.html", null ],
    [ "atlas::physics::vector4< JPH::Float4 >", "structatlas_1_1physics_1_1vector4_3_01JPH_1_1Float4_01_4.html", null ],
    [ "atlas::physics::vector4< JPH::Vec4 >", "structatlas_1_1physics_1_1vector4_3_01JPH_1_1Vec4_01_4.html", null ],
    [ "atlas::vk::vertex_attribute", "structatlas_1_1vk_1_1vertex__attribute.html", null ],
    [ "atlas::vk::vertex_attribute_entry", "structatlas_1_1vk_1_1vertex__attribute__entry.html", null ],
    [ "atlas::vk::vertex_input", "structatlas_1_1vk_1_1vertex__input.html", null ],
    [ "atlas::vk::vk_buffer", "structatlas_1_1vk_1_1vk__buffer.html", null ],
    [ "atlas::vk::vk_buffer_info", "structatlas_1_1vk_1_1vk__buffer__info.html", null ],
    [ "atlas::vk::vk_driver", "classatlas_1_1vk_1_1vk__driver.html", null ],
    [ "atlas::vk::vk_filter_range", "structatlas_1_1vk_1_1vk__filter__range.html", null ],
    [ "atlas::vk::vk_image", "structatlas_1_1vk_1_1vk__image.html", null ],
    [ "atlas::vk::vk_image_handle", "structatlas_1_1vk_1_1vk__image__handle.html", null ],
    [ "atlas::vk::vk_physical_driver", "classatlas_1_1vk_1_1vk__physical__driver.html", null ],
    [ "atlas::vk::vk_queue_options", "structatlas_1_1vk_1_1vk__queue__options.html", null ],
    [ "atlas::vk::vk_renderpass_options", "structatlas_1_1vk_1_1vk__renderpass__options.html", null ],
    [ "atlas::vk::vk_shader_module", "structatlas_1_1vk_1_1vk__shader__module.html", null ],
    [ "atlas::vk::vk_swapchain", "classatlas_1_1vk_1_1vk__swapchain.html", null ],
    [ "atlas::memory::weak_ptr< T >", "classatlas_1_1memory_1_1weak__ptr.html", null ],
    [ "atlas::window", "classatlas_1_1window.html", [
      [ "atlas::vk::vk_window", "classatlas_1_1vk_1_1vk__window.html", null ]
    ] ],
    [ "atlas::window_settings", "structatlas_1_1window__settings.html", null ],
    [ "atlas::world_scope", "classatlas_1_1world__scope.html", null ]
];