/**
 * @file string_utils.h
 * @author Generated by ChatGTP
 * @brief This is a test!
 * @version 0.0.01a
 * @date 2025-01-11
 * 
 * @copyright Apache 2.0 2025
 * 
 */

#pragma once

#include <string>
#include <vector>

/**
 * @brief String class
 * 
 */
class string_utils {
public:
    /**
     * @brief Counts the number of vowels in a string.
     * 
     * @param input The string to analyze.
     * @return The number of vowels in the string.
     * 
     * @warning Assumes ASCII input. Non-ASCII characters are ignored.
     */
    static int countVowels(const std::string& input);

    /**
     * @brief Checks if a string is a palindrome.
     * 
     * @param input The string to check.
     * @return `true` if the string is a palindrome, otherwise `false`.
     * 
     * @remark Ignores case and non-alphanumeric characters.
     */
    static bool isPalindrome(const std::string& input);

    /**
     * @brief Trims whitespace from both ends of a string.
     * 
     * @param input The string to trim.
     * @return A trimmed version of the input string.
     */
    static std::string trim(const std::string& input);
};
